#services:
#  sign-server:
#    image: "sign-server:latest"
#    container_name: "sign-server"
#    hostname: "sign-server"
#    build:
#      context: ./apps/sign-server
#      dockerfile: Dockerfile
#    ports:
#      - "9999:9999"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://sign-server:9999/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    deploy:
#      update_config:
#        delay: 10s
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s