server:
  port: 8085
spring:
  application:
    name: ssa-service
  security:
    oauth2:
      authorizationserver:
        endpoint:
          jwk-set-uri: http://localhost:8080/realms/as-realm/protocol/openid-connect/certs
fcm:
  base-url: https://fcm.googleapis.com/v1/projects/
  project-id: esign-dattb
  notification-endpoint: /messages:send
  path-to-service-account-key: /home/dattb/service-account.json