server.port=8083
spring.application.name=e-sign-service
#database postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/e-contract
spring.datasource.username=dattb
spring.datasource.password=dattb123
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=Master-HikariPool-1
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:db/master/master-changelog.xml
spring.liquibase.url=jdbc:postgresql://localhost:5432/e-contract
spring.liquibase.user=dattb
spring.liquibase.password=dattb123
spring.liquibase.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=true


#spring.datasource.master.url=jdbc:postgresql://postgres:5432/e-contract
spring.datasource.master.url=jdbc:postgresql://localhost:5432/e-contract
spring.datasource.master.username=dattb
spring.datasource.master.password=dattb123
spring.datasource.master.hikari.minimum-idle=5
spring.datasource.master.hikari.maximum-pool-size=20
spring.datasource.master.hikari.idle-timeout=30000
spring.datasource.master.hikari.pool-name=Master-HikariPool-1
spring.datasource.master.hikari.max-lifetime=1800000
spring.datasource.master.driver-class-name=org.postgresql.Driver

spring.datasource.tenant.hikari.minimum-idle=5
spring.datasource.tenant.hikari.maximum-pool-size=20
spring.datasource.tenant.hikari.idle-timeout=30000
spring.datasource.tenant.hikari.pool-name=Tenant-HikariPool-1
spring.datasource.tenant.hikari.max-lifetime=1800000
spring.datasource.tenant.hikari.connection-timeout=30000
spring.datasource.tenant.hikari.driver-class-name=org.postgresql.Driver

minio.storage.access-key=b1XiMaEdnvHEA3WOXfDr
minio.storage.secret-key=SUPKvfn2ZFeMLZcOexO7O01nTzB3Ekv3WH8quY38
minio.storage.bucket-name=e-contract
minio.storage.endpoint=http://localhost:9000
minio.storage.kms-key=E8gT8GjBdR1m3hQ3n2cPw/vY8M5BqOHwOoyIRh2vK8c=
minio.storage.kms-key-id=E8gT8GjBdR1m3hQ3n2cPw/vY8M5BqOHwOoyIRh2vK8c=
minio.storage.region=us-east-1
